version: 1.0.31.{build}

image:
  - Visual Studio 2017

environment:
  matrix:
    - compiler: clang-cl
      generator: Ninja
      build_group: Continuous
      msvc_setup_path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
      msvc_setup_arg: x86_amd64
    - compiler: msvc
      generator: Visual Studio 15 2017 Win64
      build_group: Continuous

matrix:
  # Build frequently times out.
  allow_failures:
    - compiler: msvc
      configuration: Debug

configuration:
  - Release
  - Debug

platform:
  - x64

clone_depth: 1

install:
  - ps: $project_dir="$pwd";
  - ps: .\build\scripts\appveyor.install.windows.ps1
  - ps: $env:Path += ";C:\third_party\installs\Ninja;$env:WIX"
  - ps: $env:CMAKE_TOOLCHAIN_FILE = "c:\third_party\installs\vcpkg-export\scripts\buildsystems\vcpkg.cmake"
  - ps: $env:VCPKG_TARGET_TRIPLET = "x64-windows-static"
  - ps: $env:PreferredToolArchitecture = "x64"

before_build:
  - if DEFINED msvc_setup_path call "%msvc_setup_path%" %msvc_setup_arg%
  - set DOGEN_PROJECTS_DIRECTORY=%APPVEYOR_BUILD_FOLDER%\projects
  - set CPP_REF_IMPL_PROJECTS_DIRECTORY=C:\third_party\ref_models\cpp_ref_impl-master\projects
  - set FROZEN_PROJECTS_DIRECTORY=C:\third_party\ref_models\frozen-master\projects
  - set CSHARP_REF_IMPL_PROJECTS_DIRECTORY=C:\third_party\ref_models\csharp_ref_impl-master\Src
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - ps: $env:BUILD_PROVIDER = "appveyor"
  - ps: $env:BUILD_COMMIT = $env:APPVEYOR_REPO_COMMIT
  - ps: $env:BUILD_NUMBER = $env:APPVEYOR_BUILD_VERSION
  - ps: $env:BUILD_TIMESTAMP = Get-Date -format "yyyy/MM/dd HH:mm:ss"
  - ps: ctest --extra-verbose --script ".ctest.cmake,configuration_type=$env:configuration,generator=$env:generator,compiler=$env:compiler,build_group=$env:build_group,minimal_packaging=1,boost_test_reporting=1";

on_finish:
  - ps: Invoke-WebRequest https://report.ci/upload.py | Select-Object -ExpandProperty Content | python - --name "Windows $env:compiler $env:configuration"

artifacts:
  - path: build\output\clang-cl\Release\stage\pkg\DOGEN-1.0.31-Windows-AMD64.msi
    name: x86_64 MSI

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/b6954fae540d73da033b
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
  - provider: Email
    to:
      - marco.craveiro@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

deploy:
  - provider: BinTray
    username: mcraveiro
    api_key:
      secure: aeW66aeBxn5W4wOnb5Ae9L1/dYRsAyWiJatWTpKPSwEgR1diIFPUUeSqQ4jTxeF8
    subject: masd-project
    repo: main
    package: dogen
    artifact: build\output\clang-cl\Release\stage\pkg\DOGEN-1.0.31-Windows-AMD64.msi
    version: 1.0.31
    publish: true
    override: true
