version: 2.2.{build}

branches:
    only:
        - master

environment:
  matrix:
    # - generator: "MinGW Makefiles"
    - generator: "Visual Studio 14 2015 Win64"

configuration:
  - Debug
  - Release

platform:
  - x64

clone_depth: 5

install:
    - cinst cmake --version 3.4.3

    # conan
    - cmd: echo "Installing conan..."
    # - ps: wget http://downloads.conan.io/latest_windows -OutFile conan_installer.exe
    - cmd: set PYTHON="C:/Python27"
    - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
    - cmd: pip.exe install conan
    # - cmd: conan_installer.exe /VERYSILENT
    - cmd: set PATH=%PATH%;C:\Program Files (x86)\Conan\conan
    - cmd: conan --version

before_build:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - cmd: set PATH=C:\MinGW\bin;%PATH%
  - cmd: cd build
  - cmd: mkdir output
  - cmd: cd output
  - cmd: if "%configuration%"=="Release" conan install ../.. --file=.conanfile.txt
  - cmd: if "%configuration%"=="Debug" conan install ../.. --file=.conanfile.txt -s compiler="Visual Studio" -s compiler.version=14 -s arch=x86 -s build_type=Debug -s compiler.runtime=MDd
  - cmd: cmake ../.. -DCMAKE_BUILD_TYPE=%configuration% -G "%generator%"

build_script:
  # FIXME: different levels of borkage atm.
  - cmd: if "%configuration%"=="Release" cmake --build . --config "%configuration%"
  - cmd: if "%configuration%"=="Debug"  cmake --build . --config "%configuration%" --target knit
  # - cmd: cmake --build . --config "%configuration%" --target run_all_tests

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/414a6b420bdcead8eec0
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
  - provider: Email
    to:
      - marco.craveiro@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
